keys:
  - &denzo age1re0wm49f2apw22f0e2ewtwejvxmfy9wf78tdusxgwy5drd0qf35qy90k59
  - &nixbox age19wna8h6j5grzpqj5x8f7v0qpehwvj0dfgfyytc5m7rtz9gmztpzsvwncty
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *denzo
      - *nixbox