acme:
    porkbun: ENC[AES256_GCM,data:jOJped8qyqo+2HM0PDnxj8u+/cQDZT8nP62HE1be79/8mBRZKl41U99LsCEurkkAm52rbr4R6nGTHhKwJaJdfXK8whugCAAeM/4OkShSMJKiBRJnKRtocCyfifKyXFRzrSI8ZdnMj8eSR8gW8htgrCwED4Xex0dRQmMjBzoPJumL1jNdmCt+xoQhVtdiIhDfNIn5ni2OMzbE9ScHk2TvOuJsBET+Re1WkUePKR7hT7V1,iv:gPfNq01fg+VN2pLpH5hLJ/0GILcdEBYCnYjYWfbbfUM=,tag:RZWM6TGSNwvx63pmVM7YZQ==,type:str]
borg:
    ssh_private_key: ENC[AES256_GCM,data:KR0AqYv+v2s3XQW/F/IUiEpzTF8yHhzqA2SNflpQG4ouiXMkRBh7yYpTqGnBJ6ndDpToM5BxIQ1a+t85NJz8/MeHu6GWdftbDOreCqQ5ltyO+KhzLzjHEhXdVAcxQRQEUN0Jf8ELZqjg4zOeVlFOM3F4/3q9vKugcnSJxXRt/MjVQlMTLmPy9b9WZ3snhBEfvAOX1gO0pl6myLmNcQVGoStMS3E6+8jy3KwuDxVA+4R1a1cvfaFNLooc9rLZO2Esx00aVcKaPk43P0o01URv9ulQUmiorwQ8ZJBjAqhh1zffEImDCWy3eZeLYHEyLBtHTjVg2KirZVYriFvi5NJID3zIX5DsNR0kPPyOembQpB36vhIl4tsqbSng2sVpSnxHBxvpCSUOubvPFHyV5ndtri1azsWzBKj0hdGHiaF53y76mEc8b7UN/7LpGbU+eO7XmAdqOq32xyRY+ps2lrtNEeUC63bGf7AcWbGCKwn+JXrYhLDTkgMgb8s3T5pVtvzFo2bDDESnVDUpFVHf35Sq,iv:r2YpbfrKoWdIrNubGNd0BiR1pSZyfQO5PvidtVoLOzA=,tag:TM5OWeoBztymDVttYxbKhw==,type:str]
    passphrase: ENC[AES256_GCM,data:yGGrNVgm5uRkZyQijfU6vTxiMWlU2COdlvvxmJYAsn31c/zmiiIzS+AhjZkjuAjtxgCOLoDBL/8y5ZtS8+Bv67hk2zeLpWPliBHOFH76k53X1nIhk6rfMFJwz3vWPJhO7ugSjg==,iv:2Z+fdd386Ey4Lq4SAxQHAnKi4fHTar1DXLHl0yFHiR0=,tag:r2y7s9yPUFmYYiQuRKuvpw==,type:str]
cs2mqtt: ENC[AES256_GCM,data:pzLCoQTNZg24RzgvNFs8sRVfbYk22LbOak6SAZ5vOyIFBuXIfN57QSIOty9NvxuMN07IlLofjuPmx41P,iv:IH4jzLX63hcWAuyulVHbUjeE+ZZ8pExUa14AAGE9R5k=,tag:oA6ecP/4VnewFx71puzk3A==,type:str]
forgejo:
    adminUser: ENC[AES256_GCM,data:vJ6fyHw=,iv:g3o3rUOvB79lJZJPAaHatwo4AnpJ6LV5ILvrJPSEWtE=,tag:jF53kd4bWxnP6r0YB4hlpQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:X/lUXY2Yv8vGLgzJKG7k5CCZGVU2TUa8,iv:CX2cqrjFV0YKesZSl7KAAVTi8q8QuQWSkeLBCu7VCiw=,tag:eSs2g2pT/h/MwEZjoOC/PQ==,type:str]
    runnerToken: ENC[AES256_GCM,data:3CQDuSuTYN2mK8TL5crU3c5octslBrZ48zr1yko3agGmbbEUGW3s3EE6RcWpmCulZQk=,iv:zZFiWAL7bo5tLGgD06/0/pGQqvgvT6HgWaNsvGyxveA=,tag:U4nOFTF+59/pXQW7nljFZA==,type:str]
homeassistant: ENC[AES256_GCM,data:eQ6xdqyKYTLhQNXYbQc00eFJnCmXxIHTPOD8ExI6Ixvq8Y8UXi7tYdaYkmKNNZhbrN4yXnspLAeIUCkE3VkOyrTEof7ACKXy4iBQq4izHzQqgoUAuArLAqyTNZ4Z6qCtCtQWBsx7aWARF2GMGIarr3lqRqcVKATv9N98FEC7K9A+TrIdnrRqQkCJtkoNyzIfr7Xb5Zq63LYWP776x6Y8OPNTX5e8L7HztGZwGHkAz91J7iBwL/w90ZNLOdxKpkzcd7QZTpNp8/i8sI1NWGwIGebYYslezVu0GHVdkn3BcoqniyjpLYGS1UPJQszGM7YqS+/Z8F33hA==,iv:cxUqJu4BO5Og1a65831yWAi/epCf9RBF0pYCvfo4W7c=,tag:ARqar3v6vwtrVefCBTVD7A==,type:str]
mosquitto:
    hass_password: ENC[AES256_GCM,data:O811t7hu0hf/jCKDJsXV/w5jHV4FODN1VAe+COlN28OkhrvLqIC8yrLH70l//nOp6/VgFu2ddvKEMBo0wbLLb8FwYWenX12O7TAYA1D4HcuLQno2312DwWgO3Fd75szltPwaXdcwUoIBoPgEhlUYhg==,iv:VZ+ZJQ1R4lsfcQo+xBahbxWd8P7MM5j9JQpFr4R412Q=,tag:d4GkMPLxMCn8y0KUnDKQmA==,type:str]
tailscale:
    authKey: ENC[AES256_GCM,data:VJrcmO990zEcG974ujAVuf0ilxu9G7HMsGUsJBL7h1q+w4SHncVSqlSwQkqzbJtXsevRsT70I0BuaqbvHg==,iv:/f6conmLeenFCtGuLzhvx6yNwBjoaog3umphUS0AsLA=,tag:MCw2YO4aOCF32T5vqnkcAw==,type:str]
zigbee2mqtt:
    secret.yaml: ENC[AES256_GCM,data:K7R3x4Ppe1tdCFb9X6pGN4fVyUPSXVPaN7OxJuc5mySiYOREyUUhueXZCKeofVp+v1NA95s4Cg18T6tNiWHmHDBJS8q96NxHD61d8NA=,iv:NbZ+hdH3lzZK0I6yLEyqb3jAxwbGCmOwunw2exsreCE=,tag:bix0D0lO2lxspQw2TY85GA==,type:str]
ntfy:
    environment: ENC[AES256_GCM,data:3coBMpssHYaomKVyOjvWPI7fhXUnVjrckjTUgaXhnENP1w21IxTfvbqth7CyRvlIFlWC7g5DyDtHdr/23XKnOmmNN/Fn,iv:8m2Fki7gKf86Snm4jkrPVdXa++QI7jp1EkYTOpuaPLs=,tag:hCZR2NqGZkbO7247YGp2FA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Tmk4REk2VXVkemkrY0lz
            d3F0WWJ4blVYeE8yZEtnZkZ6UzNQSmpUODE0CjR6a2l5ZDdEQnhLaUNhaDR3a09C
            SE0zSTdTVjUxdDY5cnVDbjQrMlExRUEKLS0tIGdISGZXSzdUcFpZL3Z5dlRVaXl2
            K0xoZGVDcWFSSGZFWWJFaFJPeGJLWmMKgD1fZhiBq0oWlVeKMjVaMtcf2lhKkrTp
            HHiOykm9p8inxowMuPyaXwMUYp7ABGtV7xOZogQFwU4tMzoBOyZPCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1re0wm49f2apw22f0e2ewtwejvxmfy9wf78tdusxgwy5drd0qf35qy90k59
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNW9ENW9jSTIrM2NhWVha
            cm04M0Q1VE1yK3gvL0ZZUjVMempPenU4V3k4CjlPWTFqWUZKRmhnRG1JN21nd21K
            em9SUTZTeTVvVjJmRzlSQmlPT3pMUVkKLS0tIG13a1J6Y1JBaHJxWmczWkZsOW1r
            L1ZNZElWNWp1NU0xaXgreVBwQXdZdE0KTJWEehqB6O5WvVDvkX75HPII7yV7ShVH
            cAThfZ/U7Fx2sVV8aRM7RhHUBDK142QLYB1tKTY/oz8skZUpW1o+SA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19wna8h6j5grzpqj5x8f7v0qpehwvj0dfgfyytc5m7rtz9gmztpzsvwncty
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNFBZbTdRYVBNWmpVczdy
            eHZVcjFPcXBvalJrQm9BSVZwdFJFSmtQQ0VvCkE3MllCVzJrYnpEUlJhR1hTSjdt
            NkFzb3hjQmVVL3FsT2dScGc5YXdCdDgKLS0tIElqNTIydTBEeVh2d1lUNTFmZ2ZQ
            M0RHUjR0NXo1YzZCSEx3eDBPSkkyblEKX44QqmqnG5Eieq1p3QSg1SsnQiakl/iO
            +iuyVbK4mz5NcCQNwuFlt1W2sHfDsCD4nm4UmV1oNHQs72LDKeeScQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfcr658xw3l8w4m86tgxhn4jqnv9nxzhyk40q55229nhlgm8xaeqc8ggzy
    lastmodified: "2026-07-04T13:58:56Z"
    mac: ENC[AES256_GCM,data:r7GoTeSLE/ypFerm5ectb7kwL8eZMiI+FUUVs9Y4O+NlkMnw/Df3iH2GeJTgVZQF0UFlqJWndwltTW7b7d3Gas1kYcswIp2nqj55ZdObNLEIf/oLvimGRBgpcqnatod1xnkCdjRhiTxRbLUdhBPphjua8wVBRWVpcrF+rWOgesA=,iv:OVnrC1TOcE4g0VIz/mcBhNjhJH8zaZ1eML599xpv9l4=,tag:pjs6xRGpPIEs19qX7xoVoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
